### ISSUE TITLE
/client/documents no retorna xml y pdf

### ISSUE THREAD

**Issue by jhenrygv** [giansalex/sufel-rest#2]
Hola @giansalex , estoy haciendo unas pruebas del servicio y no me retorna los campos xml y pdf, pienso que es el link para q descargue ..

![captura](https://user-images.githubusercontent.com/424193/53124284-f6f92d80-3528-11e9-9f94-696aa473a3f1.PNG)

**Comment by giansalex** [comment]
Hola @jhenrygv, gracias por la observación. En ese caso no devuelve esa informacion (xml, pdf), para descargar esos archivos se usa `/client/documents/{id}/resource/{type}` .

Se reutilizo el modelo, pero para evitar confusión esos campos serán quitados.
